// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxmodelreflection.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class TestThePattern extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __TestPatternObj;
	private mxmodelreflection.proxies.TestPattern TestPatternObj;

	public TestThePattern(IContext context, IMendixObject TestPatternObj)
	{
		super(context);
		this.__TestPatternObj = TestPatternObj;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.TestPatternObj = this.__TestPatternObj == null ? null : mxmodelreflection.proxies.TestPattern.initialize(getContext(), __TestPatternObj);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestThePattern";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
